// <auto-generated />
using System;
using ClientReportManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientReportManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientReportManager.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("EstadoClienteIdEstadoCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCliente")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TipoClienteIdTipoCliente")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.HasIndex("EstadoClienteIdEstadoCliente");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.HasIndex("TipoClienteIdTipoCliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ClientReportManager.Models.EstadoCliente", b =>
                {
                    b.Property<int>("IdEstadoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadoCliente");

                    b.ToTable("EstadosCliente", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoCliente = 1,
                            Activo = true,
                            Nombre = "Activo"
                        },
                        new
                        {
                            IdEstadoCliente = 2,
                            Activo = true,
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            IdEstadoCliente = 3,
                            Activo = true,
                            Nombre = "Potencial"
                        });
                });

            modelBuilder.Entity("ClientReportManager.Models.TipoCliente", b =>
                {
                    b.Property<int>("IdTipoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoCliente");

                    b.ToTable("TiposCliente", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoCliente = 1,
                            Activo = true,
                            Nombre = "Individual"
                        },
                        new
                        {
                            IdTipoCliente = 2,
                            Activo = true,
                            Nombre = "Empresa"
                        },
                        new
                        {
                            IdTipoCliente = 3,
                            Activo = true,
                            Nombre = "Proveedor"
                        },
                        new
                        {
                            IdTipoCliente = 4,
                            Activo = true,
                            Nombre = "Corporativo"
                        });
                });

            modelBuilder.Entity("ClientReportManager.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            Clave = "123456",
                            Correo = "admin@demo.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Administrador del Sistema",
                            NombreUsuario = "admin"
                        });
                });

            modelBuilder.Entity("ClientReportManager.Models.Cliente", b =>
                {
                    b.HasOne("ClientReportManager.Models.EstadoCliente", "EstadoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("EstadoClienteIdEstadoCliente");

                    b.HasOne("ClientReportManager.Models.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteIdTipoCliente");

                    b.Navigation("EstadoCliente");

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("ClientReportManager.Models.EstadoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ClientReportManager.Models.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
